trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  displayName: 'Build an Image'
  inputs:
    command: build
    repository: flask
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

- task: Docker@2
  displayName: 'Push an image'
  inputs:
    containerRegistry: |
      'Docker Hub'
    repository: flask
    command: push
    tags: |
      test1
      test2