trigger:
- master

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'master'
  

stages:
- stage: 'Build'
  displayName: 'Build and Push Image'
  jobs:
  - job: 'Build_and_Push_Image'
    pool:
      vmImage: 'ubuntu-latest'

    environment: dev

    variables:
      tag: '$(Build.BuildId)'

    steps:
    - task: Docker@2
      displayName: 'docker build & docker push'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: 'maximiano86/flask'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'docker registry'
        tags: |
          $(tag)

- stage: 'Dev'
  displayName: 'Deploy Dev Environment'
  dependsOn: Build
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
    )
  jobs:
  - job: 'deploys_to_dev'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: CmdLine@2
      displayName: 'Just another echo'
      inputs:
        script: echo 'this is another stage' 

- stage: 'Prod'
  displayName: 'Deploy Prod Environment'
  dependsOn: Build

  jobs:
  - job: 'deploys_to_dev'
    pool:
      vmImage: 'ubuntu-latest'
    
    environment: prod

    steps:

    - task: KubernetesManifest@0
      displayName: 'Deploy to Kubernetes cluster'
      inputs:
        action: deploy
        kubernetesServiceConnection: 'azure-k8s-dev'
        namespace: 'default'
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yml
        containers: |
          $(RegistryName)/python-flask:$(tag)

