trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and push image to container registry'
  inputs:
    command: buildAndPush
    buildContext: $(Build.Repository.LocalPath)
    repository: 'maximiano86/flask'
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    containerRegistry: 'docker registry'
    tags: |
      $(tag)