trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  displayName: 'Build an Image'
  inputs:
    command: build
    repository: flask
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'